
#include "stm32f10x.h"
#include "gpio.h"
#include "timer.h"

#include <stdio.h>
#include <stdbool.h>

void test1() {
	return;
}

int main (void)
{
	GPIO_Enable(GPIOA);
	GPIO_Enable(GPIOB);
	GPIO_Enable(GPIOC);
	
	Timer_Enable(TIM1, 548, 65535);
	
	GPIO_Set_Config(TIM1_CHANNEL_1_GPIO, TIM1_CHANNEL_1_PIN, OUTPUT_2MHZ, O_ALTERNATE_GPO_PUSH_PULL);
	GPIO_Set_Config(TIM1_CHANNEL_2_GPIO, TIM1_CHANNEL_2_PIN, OUTPUT_2MHZ, O_ALTERNATE_GPO_PUSH_PULL);
	GPIO_Set_Config(TIM1_CHANNEL_3_GPIO, TIM1_CHANNEL_3_PIN, OUTPUT_2MHZ, O_ALTERNATE_GPO_PUSH_PULL);
	GPIO_Set_Config(TIM1_CHANNEL_4_GPIO, TIM1_CHANNEL_4_PIN, OUTPUT_2MHZ, O_ALTERNATE_GPO_PUSH_PULL);
	
	// CC2E & PW MODE 1
	Timer_PWM_Enable(TIM1, TIM_CHANNEL_1, PWM_MODE_2);
	Timer_PWM_Enable(TIM1, TIM_CHANNEL_2, PWM_MODE_2);
	Timer_PWM_Enable(TIM1, TIM_CHANNEL_3, PWM_MODE_2);
	Timer_PWM_Enable(TIM1, TIM_CHANNEL_4, PWM_MODE_2);
	
	Timer_PWM_Set(TIM1, TIM_CHANNEL_1, 0xFFFF/2);	
	Timer_PWM_Set(TIM1, TIM_CHANNEL_2, 0xFFFF/3);	
	Timer_PWM_Set(TIM1, TIM_CHANNEL_3, 0xFFFF/4);	
	Timer_PWM_Set(TIM1, TIM_CHANNEL_4, 0xFFFF/5);	
	
	Timer_Start(TIM1);
	/* Tests for GPIO Driver */
	/*
	GPIO_Set_Config(GPIOB, 0, INPUT, I_FLOATING_INPUT);
	GPIO_Set_Config(GPIOB, 1, INPUT, I_ANALOG);
	GPIO_Set_Config(GPIOB, 2, INPUT, I_PULL_UP_PULL_DOWN);
	
	GPIO_Set_Config(GPIOB, 3, OUTPUT_2MHZ, O_GPO_OPEN_DRAIN);
	GPIO_Set_Config(GPIOB, 4, OUTPUT_2MHZ, O_GPO_PUSH_PULL);
	GPIO_Set_Config(GPIOB, 5, OUTPUT_2MHZ, O_ALTERNATE_GPO_OPEN_DRAIN);
	GPIO_Set_Config(GPIOB, 6, OUTPUT_2MHZ, O_ALTERNATE_GPO_PUSH_PULL);
	
	GPIO_Set_Config(GPIOB, 7, OUTPUT_10MHZ, O_GPO_OPEN_DRAIN);
	GPIO_Set_Config(GPIOB, 8, OUTPUT_10MHZ, O_GPO_PUSH_PULL);
	GPIO_Set_Config(GPIOB, 9, OUTPUT_10MHZ, O_ALTERNATE_GPO_OPEN_DRAIN);
	GPIO_Set_Config(GPIOB, 10, OUTPUT_10MHZ, O_ALTERNATE_GPO_PUSH_PULL);
	
	GPIO_Set_Config(GPIOB, 11, OUTPUT_50MHZ, O_GPO_OPEN_DRAIN);
	GPIO_Set_Config(GPIOB, 12, OUTPUT_50MHZ, O_GPO_PUSH_PULL);
	GPIO_Set_Config(GPIOB, 13, OUTPUT_50MHZ, O_ALTERNATE_GPO_OPEN_DRAIN);
	GPIO_Set_Config(GPIOB, 14, OUTPUT_50MHZ, O_ALTERNATE_GPO_PUSH_PULL);
	*/
	
	while (1)
	{
	}
}

